food = 'PIZZA margarita'
print(food.lower())
print(food.upper())
print(food.capitalize())
print(food.title())
print(food.strip())
print(food.find('mar'))
print(food.replace('margarita', 'pepperoni'))
print(food.replace('margarita', 'pepperoni').title())
print('margarita' in food)
print('margarita' not in food)
